# Configuracao para Readme-Workflows/recent-activity@v2.4.1
settings:
  username: devimploy
  limit: 5
  readme_file: ./README.md
  commit_message: "⚡ [BOT] Auto-update: atividade recente do GitHub"

messages:
  push: "⬆️ Fez push de commits para {REPO}"
